---
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "123"
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - 192.18.0.2:53
profile:
  store-selected: true
  store-fake-ip: true

# ================= Coders Family ==================
proxy-providers:
  PP-Final:
    type: file
    path: "./proxy_provider/bebas.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
  PP-Indonesia:
    type: file
    path: "./proxy_provider/indonesia.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
# ================= Coders Family ==================
proxy-groups:
  - name: Final
    type: url-test
    disable-udp: false
    use:
      - PP-Final
    url: http://www.gstatic.com/generate_204
    interval: '100'
  - name: Indonesia
    type: url-test
    disable-udp: false
    use:
      - PP-Indonesia
    url: http://www.gstatic.com/generate_204
    interval: '100'

  - name: Mode Indonesia
    type: url-test
    disable-udp: false
    proxies:
      - Indonesia
      - Final
      - DIRECT
      - REJECT 
  - name: Akrab
    type: select
    proxies: [Final,DIRECT,REJECT]
  - name: Vision
    type: select
    proxies: [Final,DIRECT,REJECT]
  - name: Youtube
    type: select
    proxies: [Final,Indonesia,DIRECT,REJECT]

dns:
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
    - '+.lan'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'proxy.golang.org'
    - '+.msftconnecttest.com'
    - '*.home.arpa'
    - '*.local'
    - '*.test'
    - '*.localhost'
    - '*.invalid'
    - '*.example'
    - '*.localdomain'
    - '*.lan'
    - 'localhost'
    - '0.id.pool.ntp.org'
    - '1.id.pool.ntp.org'
    - '2.id.pool.ntp.org'
    - '3.id.pool.ntp.org'
  default-nameserver:
    - 'https://1.1.1.1/dns-query'
    - 'tcp://1.0.0.1'
    - '112.215.248.124#REJECT'     ## dns xl di reject
  fallback:
    - '1.1.1.1#Final'
  fallback-filter:
    geoip: true
    geoip-code: 'ID'
    geosite: [gfw]
    ipcidr: 
      - 0.0.0.0/8
      - 127.0.0.0/8
      - 123.123.123.0/24
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.zoom.us'
      - '+.visionplus.id'
      - '+.facebook.com'
      - '+.youtube.com'
rule-providers:
### classical / ipcidr / domain
  RP_Direct:
    type: file
    behavior: classical
    path: "./rule_provider/rule-direct.yaml"
  RP_Reject:
    type: file
    behavior: classical
    path: "./rule_provider/rule-reject.yaml"
  RP_WhatsApp:
    type: file
    behavior: classical
    path: "./rule_provider/rule-whatsapp.yaml"
  RP_Line:
    type: file
    behavior: domain
    path: "./rule_provider/rule-line.yaml"
  RP_Lan_Domain:
    type: file
    behavior: domain
    path: "./rule_provider/rule-lan-domain.yaml"
  RP_Lan_IP:
    type: file
    behavior: ipcidr
    path: "./rule_provider/rule-lan-ip.yaml"
  RP_DNS:
    type: file
    behavior: classical
    path: "./rule_provider/rule-dns.yaml"
  RP_Video:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-video.yaml"
  RP_Musik:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-musik.yaml"
  RP_Domain_Indo:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-domain-indo.yaml"
  RP_Akaimahd:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-akaimahd.yaml"
  RP_Disney_Joox:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-disney-joox.yaml"
  RP_Market_Place:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-market-place.yaml"
  RP_Ewallet:
    type: file
    behavior: classical
    path: "./rule_provider/KhususIndo/rule-ewallet.yaml"
  RP_Akrab:
    type: file
    behavior: classical
    path: "./rule_provider/Paket/akrab.yaml"
  RP_Vision:
    type: file
    behavior: classical
    path: "./rule_provider/Paket/vision.yaml"
  RP_Youtube:
    type: file
    behavior: domain
    path: "./rule_provider/rule-youtube.yaml"  
rules:
### Anti gagal Block Ads
- DOMAIN-SUFFIX,googlesyndication.com,Final
- RULE-SET,RP_Reject,REJECT
### Paket untuk di direct
- RULE-SET,RP_Akrab,Akrab
- RULE-SET,RP_Vision,Vision
- RULE-SET,RP_Youtube,Youtube
### Fix lemot youtube
- AND,((GEOSITE, YOUTUBE),(NETWORK, UDP)),REJECT
### Domain Indo khusus VPN INDO
- AND,((DST-PORT,5228-5230),(NETWORK,TCP),(DOMAIN,mtalk.google.com)),Mode Indonesia
- RULE-SET,RP_Video,Mode Indonesia
- RULE-SET,RP_Musik,Mode Indonesia
- RULE-SET,RP_Disney_Joox,Mode Indonesia
- RULE-SET,RP_Akaimahd,Mode Indonesia
- RULE-SET,RP_Market_Place,Mode Indonesia
- RULE-SET,RP_Ewallet,Mode Indonesia
- RULE-SET,RP_Domain_Indo,Mode Indonesia
- GEOIP,ID,Mode Indonesia
### Umum
- RULE-SET,RP_Direct,DIRECT
- RULE-SET,RP_Lan_Domain,DIRECT
- RULE-SET,RP_Lan_IP,DIRECT,no-resolve
- GEOIP,private,DIRECT,no-resolve
- RULE-SET,RP_DNS,Final
### Yang tidak di rule otomatis kesini
- MATCH,Final
- MATCH,GLOBAL
