proxies:
##OVH# https://www.fastssh.com/page/create-v2ray-account/server/676714/vmess-singapore-ovh-1/
############################################
  - <<: *basevmess
    name: OVH
    server: *bvision1
    uuid: a2af0f90-a56e-11ed-b035-205c6d5f5d78
    servername: sg-2.0rd.net
    network: ws
    ws-opts: 
      path: *pathServer
      headers: 
        Host: sg-2.0rd.net
  - &fastssh
    <<: *basevmess
    name: Dynamic
    server: *bvision1
    uuid: e82cc3e2-571c-43f1-81a6-2ca24f4142dc
    servername: *dynamic1
    ws-opts:
      path: *pathServer
      headers:
        Host: *dynamic1
############################################
### Inggris
##US1# https://www.fastssh.com/page/create-v2ray-account/server/676713/vmess-united-states-1
  - <<: *basevmess
    name: US1
    server: *bvision1
    uuid: 977254d0-a683-11ed-b636-205c6d5f5d78
    servername: us-1.0rd.net
    ws-opts: 
      path: *pathServer
      headers: 
        Host: us-1.0rd.net
############################################
### Indonesia
  - &atha-fastssh
    <<: *basevmess
    name: Atha 1
    server: *bvision1
    uuid: d657d280-a567-11ed-b139-205c6d5f5d78
    servername: sg-6.0rd.net
    ws-opts: 
      path: *pathServer
      headers: 
        Host: sg-6.0rd.net
  - <<: *atha-fastssh
    name: Atha 2
    server: *bvision1
    uuid: 3e7dd760-a56a-11ed-b533-205c6d5f5d78
    servername: *sAmp2
    ws-opts: 
      path: *pathServer
      headers: 
        Host: *sAmp2
### Percobaan BUG
  - <<: *fastssh
    name: *bvision1
    server: *bvision1
  - <<: *fastssh
    name: *bvision2
    server: *bvision2
  - <<: *fastssh
    name: *bvision3
    server: *bvision3
  - <<: *fastssh
    name: *bvision4
    server: *bvision4
proxy-providers:
############################################
proxy-groups:
  - <<: *bestping
    name: Best Ping
    proxies:
      - Dynamic
      - OVH
############################################
  - <<: *bestping
    name: Indonesia
    proxies:
      - Atha 1
      - Atha 2
############################################
  - <<: *bestping
    name: English
    proxies:
      - US1
############################################
  - <<: *bestping
    name: Percobaan Bug
    proxies:
      - *bvision1
      - *bvision2
      - *bvision3
      - *bvision4
############################################
  - name: Final
    type: select
    disable-udp: false
    url: *url-cf
    interval: 200
    proxies:
      - Best Ping
      - Indonesia
      - English
############################################
  - name: Mode Indonesia
    type: select
    url: *url-cf
    interval: 200
    disable-udp: false
    proxies:
      - Indonesia
      - Final
      - English
      - DIRECT
      - REJECT
############################################
############################################
  - name: Akrab
    type: select
    proxies: [Final,DIRECT,REJECT]
  - name: Vision
    type: select
    proxies: [Final,DIRECT,REJECT]
  - name: Youtube
    type: select
    proxies: [Final,English,Indonesia,DIRECT,REJECT]
rule-providers:
### classical / ipcidr / domain
  RP_Direct:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-direct.yaml"
  RP_Reject:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-reject.yaml"
  RP_Indonesia:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-indonesia.yaml"
  RP_WhatsApp:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-whatsapp.yaml"
  RP_Line:
    type: file
    behavior: domain
    path: "./config/rule_provider/rule-line.yaml"
  RP_Lan_Domain:
    type: file
    behavior: domain
    path: "./config/rule_provider/rule-lan-domain.yaml"
  RP_Lan_IP:
    type: file
    behavior: ipcidr
    path: "./config/rule_provider/rule-lan-ip.yaml"
  RP_DNS:
    type: file
    behavior: classical
    path: "./config/rule_provider/rule-dns.yaml"
  RP_Video:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-video.yaml"
  RP_Musik:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-musik.yaml"
  RP_Domain_Indo:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-domain-indo.yaml"
  RP_Akaimahd:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-akaimahd.yaml"
  RP_Disney_Joox:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-disney-joox.yaml"
  RP_Market_Place:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-market-place.yaml"
  RP_Ewallet:
    type: file
    behavior: classical
    path: "./config/rule_provider/KhususIndo/rule-ewallet.yaml"
  RP_Akrab:
    type: file
    behavior: classical
    path: "./config/rule_provider/Paket/akrab.yaml"
  RP_Vision:
    type: file
    behavior: classical
    path: "./config/rule_provider/Paket/vision.yaml"
  RP_Youtube:
    type: file
    behavior: domain
    path: "./config/rule_provider/rule-youtube.yaml"
rules:
### Anti gagal Block Ads
  - DOMAIN-SUFFIX,googlesyndication.com,Final
  - RULE-SET,RP_Reject,REJECT
### Paket untuk di direct
  - RULE-SET,RP_Akrab,Akrab
  - RULE-SET,RP_Vision,Vision
  - RULE-SET,RP_Youtube,Youtube
### Fix lemot youtube
  - AND,((GEOSITE, YOUTUBE),(NETWORK, UDP)),REJECT
### Domain Indo khusus VPN INDO
  - AND,((DST-PORT,5228-5230),(NETWORK,TCP),(DOMAIN,mtalk.google.com)),Mode Indonesia
  - RULE-SET,RP_Indonesia,Mode Indonesia
### Umum
  - RULE-SET,RP_Direct,DIRECT
  - RULE-SET,RP_Lan_Domain,DIRECT
  - RULE-SET,RP_Lan_IP,DIRECT,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - RULE-SET,RP_DNS,Final
### Yang tidak di rule otomatis kesini
  - MATCH,Final
  - MATCH,GLOBAL
