proxies:
### Config ada di folder Backup
  - name: vmess-biasa
    server: server.com
    port: 443
    type: vmess
    uuid: xxxx-xxxx-xxxx-xxxx-xxxx
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sni.bug
    network: ws
    ws-opts: 
      path: /path-vmess
      headers: 
        Host: sni.bug
    udp: true